"""Add task status

Revision ID: 12c6ac752bb4
Revises: 9369c1199146
Create Date: 2024-07-18 23:55:28.848604

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12c6ac752bb4"
down_revision: Union[str, None] = "9369c1199146"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("task_status", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "task_status")
    # ### end Alembic commands ###
